# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TheMovieDBApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TheMovieDBApp
  pod 'SwiftLint'
  pod 'KeychainAccess'
  pod 'RealmSwift'

  target 'TheMovieDBAppTests' do
    inherit! :complete
    # Pods for testing
  end

  target 'TheMovieDBAppUITests' do
    # Pods for testing
  end

end

target 'DAO' do
  use_frameworks!
  pod 'RealmSwift'
end
